### ISSUE TITLE
502 Bad Gateway on valid payments request

### ISSUE THREAD

**Issue by ace-subido** [stellar/bridge-server#83]
I have 2 integration tests against a bridge server configured to talk to `https://horizon-testnet.stellar.org` on a kubernetes pod in Google Cloud.

The first test submits an invalid payment request, and the test succeeds its expectation. The expectation is to receive an `invalid_parameter` code. Attached is a VCR (ruby) record of the request and response. It includes the details of the request/response:

```
- request:
    method: post
    uri: https://[REDACTED_SERVER_URL]/payment
    body:
      encoding: UTF-8
      string: amount=200.0&asset_code=PHP&asset_issuer=GCBEJ5SNCV4B3E2TEDEUNR7DSC7Y4RLFAGSPNKZGNIOHQFWBHXCMMHZA&destination=invalid_refund_account&memo=1234ASDF&memo_type=text&source
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Content-Type:
      - application/x-www-form-urlencoded
      Expect:
      - ''
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Content-Length:
      - '173'
      Content-Type:
      - application/json
      Date:
      - Wed, 06 Dec 2017 11:18:53 GMT
    body:
      encoding: UTF-8
      string: |-
        {
          "code": "invalid_parameter",
          "message": "Invalid parameter.",
          "more_info": "Destination public key must start with `G`.",
          "data": {
            "name": "destination"
          }
        }
    http_version: 
  recorded_at: Wed, 06 Dec 2017 11:18:52 GMT
```

The second test submits a valid payments request to the same bridge server. Below contains the VCR (ruby) record of the request/response:

```
- request:
    method: post
    uri: https://[REDACTED_SERVER_URL]/payment
    body:
      encoding: UTF-8
      string: amount=200.0&asset_code=PHP&asset_issuer=GCBEJ5SNCV4B3E2TEDEUNR7DSC7Y4RLFAGSPNKZGNIOHQFWBHXCMMHZA&destination=GCBEJ5SNCV4B3E2TEDEUNR7DSC7Y4RLFAGSPNKZGNIOHQFWBHXCMMHZA&memo=1234ASDF&memo_type=text&source
    headers:
      User-Agent:
      - Typhoeus - https://github.com/typhoeus/typhoeus
      Content-Type:
      - application/x-www-form-urlencoded
      Expect:
      - ''
  response:
    status:
      code: 502
      message: Bad Gateway
    headers:
      Date:
      - Wed, 06 Dec 2017 11:27:58 GMT
      Content-Length:
      - '11'
      Content-Type:
      - text/plain; charset=utf-8
    body:
      encoding: UTF-8
      string: Bad Gateway
    http_version: 
  recorded_at: Wed, 06 Dec 2017 11:27:57 GMT
recorded_with: VCR 3.0.3
```

Upon checking the logs of the bridge server, I see this:

<img width="1106" alt="logs_viewer_-_bloom_general" src="https://user-images.githubusercontent.com/730800/33660104-a351db08-dabd-11e7-8e21-711fd8c4cc65.png">

Here's another screenshot expanding the top of the stacktrace:

<img width="1146" alt="logs_viewer_-_bloom_general" src="https://user-images.githubusercontent.com/730800/33660157-da41bd04-dabd-11e7-89fd-893f29912f99.png">

I immediately went inside the pod and ran `curl https://horizon-testnet.stellar.org`. It brought back what was expected:

```
$ curl https://horizon-testnet.stellar.org

{
  "_links": {
    "account": {
      "href": "https://horizon-testnet.stellar.org/accounts/{account_id}",
      "templated": true
    },
    "account_transactions": {
      "href": "https://horizon-testnet.stellar.org/accounts/{account_id}/transactions{?cursor,limit,order}",
      "templated": true
    },
    "friendbot": {
      "href": "https://horizon-testnet.stellar.org/friendbot{?addr}",
      "templated": true
    },
    "metrics": {
      "href": "https://horizon-testnet.stellar.org/metrics"
    },
    "order_book": {
      "href": "https://horizon-testnet.stellar.org/order_book{?selling_asset_type,selling_asset_code,selling_issuer,buying_asset_type,buying_asset_code,buying_issuer}",
      "templated": true
    },
    "self": {
      "href": "https://horizon-testnet.stellar.org/"
    },
    "transaction": {
      "href": "https://horizon-testnet.stellar.org/transactions/{hash}",
      "templated": true
    },
    "transactions": {
      "href": "https://horizon-testnet.stellar.org/transactions{?cursor,limit,order}",
      "templated": true
    }
  },
  "horizon_version": "95b7a37",
  "core_version": "v0.6.4",
  "history_latest_ledger": 5800563,
  "history_elder_ledger": 1,
  "core_latest_ledger": 5800563,
  "core_elder_ledger": 5633216,
  "network_passphrase": "Test SDF Network ; September 2015",
  "protocol_version": 8
}
```

### Additional Information
Version: 0.0.28 linux-amd64
OS: Ubuntu 16.10
```
# bridge.cfg

port = "8001"
horizon = "https://horizon-testnet.stellar.org"
network_passphrase = "Test SDF Network ; September 2015"

[database]
type = "postgres"
url = "REDACTED_PG_URL"

[accounts]
issuing_account_id="GCBEJ5SNCV4B3E2TEDEUNR7DSC7Y4RLFAGSPNKZGNIOHQFWBHXCMMHZA"
base_seed = "REDACTED_SEED"
authorizing_seed = "REDACTED_SEED"
receiving_account_id = "GDM7HQKFNNHU5PNKTTO6EQYWG6LQ6KI3CVCEHZBW44I5GWZAQNPHF2VP"

[callbacks]
receive = "REDACTED_CALLBACK_URL"
error = "REDACTED_CALLBACK_URL"
```

### Question
Is there something on the infrastructure level that we have to look at? This test succeeds if I run this through the same image (connected to `https://horizon-testnet.stellar.org`) on a local `docker-compose` setup. 

What would be the next steps that I could take to make progress on making the test pass?

Thanks!

**Comment by ace-subido** [comment]
Hi everyone! Updates:

### Resolution

Based on research on `runtime error: invalid memory address or nil pointer dereference`. I assumed this was something low-level. I added default memory limits instead of letting kubernetes give `best_effort` memroy for the ubuntu 16.10 kubernetes pod that contained the 0.0.28.0 linux-amd64 bridge server.

```
    spec:
      containers:
        - name: bridge
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
```

Then I replaced the kubernetes pod. After the container started running, I re-ran the test. `502 Bad Gateway` was gone and I've submitted the payments request successfully. I guess we can mark this issue as closed: adding default memory limits seems to resolve the issue, but I wouldn't know the actual root cause.
